### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by CaitlinCasar** [xiaoli-dong/metaerg#7]
I've been able to run metaerg successfully with and without providing a depth file on some of my datasets using:

metaerg.pl  --dbdir /projects/p30777/db --depth /projects/p30777/metagenome_data/bams/[sample_ID]/depth.txt /projects/p30777/metagenome_data/contigs/[sample_ID]_contigs.fa --sp --tm --outdir /projects/p30777/Omics_methods_pub/metaerg/[sample_ID]_depth --force

However, on a few of my datasets (which are formatted the same way as the others) I get the error 'panic: runtime error: slice bounds out of range"  (output pasted below). Does anybody know what causes this error? Thanks!

OUTPUT: 
[Wed Dec  4 06:00:08 2019] Running: signalp -verbose=false -org gram- -format short -gff3 -tmp /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp -prefix /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa.signalp.gramn -fasta /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa
[Wed Dec  4 06:00:14 2019] Running: signalp -verbose=false -org gram+ -format short -gff3 -tmp /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp -prefix /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa.signalp.gramp -fasta /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa
[Wed Dec  4 06:00:20 2019] Running: signalp -verbose=false -org euk  -format short -gff3 -tmp /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp -prefix /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa.signalp.euk -fasta /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa
[Wed Dec  4 06:00:27 2019] Running: signalp -verbose=false -org arch -format short -gff3 -tmp /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp -prefix /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa.signalp.arch -fasta /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/tensorflow/tensorflow/tensorflow/go.tensorData(0x2b05c4001890, 0xc5ee7610c0, 0x678880, 0x6e6688)
	/home/people/jjalma/go/src/github.com/tensorflow/tensorflow/tensorflow/go/tensor.go:210 +0xa1
github.com/tensorflow/tensorflow/tensorflow/go.NewTensor(0x674000, 0xc5ee7610a0, 0x674000, 0xc5ee7610a0, 0x0)
	/home/people/jjalma/go/src/github.com/tensorflow/tensorflow/tensorflow/go/tensor.go:94 +0x221
main.main()
	/home/people/jjalma/SignalP-5.0b/signalp.go:607 +0x5870
[Wed Dec  4 12:17:24 2019] Could not run command:signalp -verbose=false -org gram- -format short -gff3 -tmp /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp -prefix /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa.signalp.gramn -fasta /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp/cds.faa, 

Perl exited with active threads:
	3 running and unjoined
	0 finished and unjoined
	0 running and detached
[Wed Dec  4 12:17:25 2019] Could not run command:/home/cpc7770/metaerginstall/bin/perl /home/cpc7770/metaerginstall/metaerg/bin/predictFeatures.pl --dbdir /projects/p30777/db --evalue 1e-05 --gtype meta --gc 11 --minorflen 180 --prefix metaerg.pl_12042019 --cpus 8 --outdir /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/tmp --sp --tm --force /projects/p30777/Omics_methods_pub/metaerg/DeMMO6_depth/metaerg.pl_12042019.fna,

**Comment by Finesim97** [comment]
Hi again, I was/am having the same problem with one of my samples. This seems to be a problem in the current SignalP version. Because the deadline for my bachelor thesis approaches I just disabled SignalP. It is weird, that the error happens in the TensorFlow library. The web service for SignalP 5 is limited to 5.000 sequences and 10.000aa long CDS. SignalP 4 had this integrated into its script. 

According to [this blogpost](https://bioengineeringcommunity.nature.com/channels/541-behind-the-paper/posts/44335-signalp-5-0-improves-signal-peptide-predictions-using-deep-neural-networks) the input layer is 70*20. The length shouldn't a problem. 

I will prepare a R script to check the length of the sequences and amino acid characters. Gram - also fails for me, but it is the first to be called, this may be just the reason for that.

**Comment by CaitlinCasar** [comment]
Ah thank you I will try running without SignalP. Good luck with your thesis!

**Comment by Finesim97** [comment]
Thank you 😊
